import random

def get_random_python_code():
    return """
# Random Python Code Generated by Math Homework Bot
x = random.randint(1, 10)
y = random.randint(1, 10)
print("The sum of", x, "and", y, "is", x + y)
"""